name: RevertEntityDropsPatch
version: '${project.version}'
main: me.itay.revertentitydropspatch.RevertEntityDropsPatch
api-version: '1.20'
load: STARTUP
authors: [Itay]
description: Revert the patch paper made (https://github.com/PaperMC/paper/commit/37bee09e3dc752327f87481bbdf28bcc511960fd ) that makes entity drops use vanilla behaviour
website: eternalanarchy.xyz
